# Generated by Django 4.0.2 on 2022-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('host_id', models.IntegerField()),
                ('host_name', models.CharField(max_length=255)),
                ('neighbourhood_group', models.CharField(max_length=255)),
                ('neighbourhood', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('room_type', models.CharField(choices=[('Entire place/apt', 'Entire Place'), ('Shared room', 'Shared Room'), ('Private room', 'Private Room')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_nights', models.IntegerField(blank=True, null=True)),
                ('number_of_reviews', models.IntegerField(blank=True, null=True)),
                ('last_review', models.DateField(blank=True, null=True)),
                ('reviews_per_month', models.FloatField(blank=True, null=True)),
                ('calculated_host_listings_count', models.IntegerField()),
                ('availability_365', models.IntegerField(blank=True, null=True)),
                ('number_of_reviews_ltm', models.IntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
